### ISSUE TITLE
createProject

### ISSUE THREAD

**Issue by stichnotht** [varioous/openproject-ticket-system#2]
Hello,

I have a mistake in my thinking somewhere. I get the following error message:

Warnung: Ungültiges Argument für foreach() in /volume1/web/openprojectmail/code.php auf Zeile 176

Warning: Invalid argument supplied for foreach() in /volume1/web/openprojectmail/code.php on line 176

Fatal error: Uncaught Error: Call to undefined method OpenProject::createProject() in /volume1/web/openprojectmail/code.php:194
Stack trace:
#0 /volume1/web/openprojectmail/index.php(80): OpenProject::createTicket(Object(PhpImap\IncomingMail), Object(PhpImap\IncomingMailHeader))
#1 {main}
  thrown in /volume1/web/openprojectmail/code.php on line 194

What can be the cause?

VG

**Comment by varioous** [comment]
Hi @stichnotht,

i have updated the code.php. Can you try it again.

Best regards,
Harald

**Comment by stichnotht** [comment]
Thank you very much, so far it works. The mails will be picked up. A project is created and the confirmation mail is sent. However a project is created but no work package. I suspect a configuration problem?
JOBS_DEFAULT_PROJECT is a numeric value, but I only have an alphanumeric identifier.
Can I get your help again?

**Comment by varioous** [comment]
Hi @stichnotht,

happy that it works now. 

You have to use get getAllProjects() function to get and see the id of a project. It is numeric, but not shown in the frontend of open project. So use this call and make a debug output of the response and check the identifier of the project that you want to use.

Best regards,
Harald

**Comment by stichnotht** [comment]
Hello, perfect, it works.
Thank you very much. A great tool!

Greetings
Thomas
